### ISSUE TITLE
A few suggestions for utils.go

### ISSUE THREAD

**Issue by yilunzhang** [omani/nkn-wallet#1]
https://github.com/omani/nkn-wallet/blob/d7de2c4ed00d14e1550d2d48a8ce85b1f5672388/utils.go#L82

The error is ignored and might cause the `encryptAccount` function to return invalid output (e.g. empty results) without any error.

https://github.com/omani/nkn-wallet/blob/d7de2c4ed00d14e1550d2d48a8ce85b1f5672388/utils.go#L34

This check seems to be fully covered by the check after for loop.

https://github.com/omani/nkn-wallet/blob/d7de2c4ed00d14e1550d2d48a8ce85b1f5672388/utils.go#L109

Just curious, what does this line do?

**Comment by omani** [comment]
hi @yilunzhang. thanks for reporting. please check out #2 . this should be it. age is fully implemented.
I will keep this issue open as a reminder for later.
